config/routes.rb
Rails.application.routes.draw do
  root to: 'public/homes#top'

  scope module: :public do
    get 'customers/mypage' => 'customers#show'
    get 'customers/introduction/edit' => 'customers#edit'
    patch 'customers/introduction' => 'customers#update'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw'

    get 'homes/about' => 'homes#about'

    resources :shipping_addresses, only:  [:index, :create, :edit, :update, :destroy]
    resources :cart_items, only: [:index, :create, :update, :destroy]do
      collection do
        delete "all_destroy"
      end
    end

    get 'items' => 'items#index'
    get 'items/:id' => 'items#show', as: 'item_show'
    get 'search' => 'searches#search'
    resources :genre_searches, only: [:show]

    get 'orders' => 'orders#index'
    get 'orders/new' => 'orders#new'
    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only:  [:create, :show]
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :genre_searches, only: [:show]
    resources :order_searches, only: [:show]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre


  validates :name, presence:true
  validates :price, presence:true, numericality: {only_integer: true, greater_than_or_equal_to: 0}



  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def add_tax_price
    (self.price * 1.10).round
  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
    if @item.update(item_params)
    redirect_to admin_item_path(@item.id)
    else
    render "edit"
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_form.html.erb
<div class="field margin-y">
  <div class="d-flex padding-sm-y">
    <%= f.label :image, "商品画像", class: "label-width" %>
    <%= f.file_field :image, accept: "image/*" %>
  </div>
  
  <div class="d-flex padding-sm-y">
    <%= f.label :name, "商品名", class: "label-width" %>
    <%= f.text_field :name, placeholder: "商品名", class: "field-width" %>
  </div>
  
  <div class="d-flex padding-sm-y">
    <%= f.label :introduction, "商品説明", class: "label-width" %>
    <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class: "field-width" %>
  </div>
  
  <div class="d-flex padding-sm-y">
    <%= f.label :genre_id, "ジャンル", class: "label-width" %>
    <%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "--選択してください--" %>
  </div>
  
  <div class="d-flex padding-sm-y">
    <%= f.label :price, "税抜価格", class: "label-width" %>
    <%= f.number_field :price, placeholder: "1000", class: "field-width" %>
    <span>円</span>
  </div>
  
  <div class="d-flex padding-sm-y">
    <p class="label-width label-name">販売ステータス</p>
    <span>
      <%= f.radio_button :is_active, true %>
      <%= f.label :is_active_true, "販売中" %>
    </span>
    <span class="margin-x">
      <%= f.radio_button :is_active, false %>
      <%= f.label :is_active_false, "販売停止中" %>
    </span>
  
  </div>
  </div>

app/views/admin/items/_items_layout.html.erb
    <table class='table table-hover margin-y table-light'>
      <thead>
        <tr>
          <th class="bg-brown">商品ID</th>
          <th class="bg-brown">商品名</th>
          <th class="bg-brown">税抜価格</th>
          <th class="bg-brown">ジャンル</th>
          <th class="bg-brown">ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item.id) %></td>
          <td><%= item.price.to_s(:delimited) %></td>
          <td><%= link_to item.genre.name, admin_genre_search_path(item.genre.id) %></td>
          <td><% if item.is_active == true %>
              <p class="text-success">販売中</p>
            <% else %>
              <p class="text-danger">販売停止中</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate items %>

app/views/admin/items/edit.html.erb
<div class="container" style="width: fit-content">
  <div class="sub_container_position">
    <h4><span>商品編集</span></h4>
    <%= form_with model: @item, url: admin_item_path do |f| %>
    <%= render "layouts/form_errors", model: @item %>
    <%= render 'admin/items/form', f: f %>
    <div class="actions text-center">
      <%= f.submit "変更を保存", class: "btn btn-success padding-x" %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container w-75">
  <div class="margin-y">
    <div class="d-flex align-items-center justify-content-between">
      <h4>商品一覧</h4>
      <%= link_to '＋', new_admin_item_path, class: "btn btn-lg btn-primary rounded-circle"%>
    </div>
      <%= render 'admin/items/items_layout', items: @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container" style="width: fit-content">
  <div class="sub_container_position">
    <h4><span>商品新規登録</span></h4>
    <%= form_with model: @item, url: admin_items_path do |f| %>
    <%= render "layouts/form_errors", model: @item %>
    <%= render 'admin/items/form', f: f %>
    <div class="actions text-center">
      <%= f.submit "新規登録", class: "btn btn-success padding-x" %>
    </div>
    <% end %>
  </div>


</div>

app/views/admin/items/show.html.erb
<div class="container">

  <h4 class="margin-y">商品詳細</h4>
  <div class='row align-items-center justify-content-center'>
    <div class='col-md-4 admin-item-image' >
      <%= image_tag @item.get_image(350, 200), class: "admin-item-image-fit", style: "width: 100%; height: 200px;" %>
    </div>

      <div class='col-md-8 mt-3'>
        <table class="table table-bordered table-light">
          <tr>
            <td class="bg-brown">商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <td class="bg-brown">商品説明</td>
            <td><%= @item.introduction %></td>
          </tr>
          <tr>
            <td class="bg-brown">ジャンル</td>
            <td><%= @item.genre.name %></td>
          </tr>
          <tr>
            <td class="bg-brown">
              税込価格
              <br>
              (税抜価格)
            </td>
            <td><%= @item.add_tax_price.to_s(:delimited) %>(<%= @item.price %>)円</td>
          </tr>
          <tr>
            <td class="bg-brown">販売ステータス</td>
            <td>
              <% if @item.is_active == true %>
                <p class="text-success">販売中</p>
              <% else %>
                <p class="text-danger">販売停止中</p>
              <% end %>
            </td>
          </tr>
        </table>
      </div>
      <div class="text-center">
          <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success padding-x" %>
      </div>

  </div>
</div>