config/routes.rb
Rails.application.routes.draw do
  root to: 'public/homes#top'

  scope module: :public do
    get 'customers/mypage' => 'customers#show'
    get 'customers/introduction/edit' => 'customers#edit'
    patch 'customers/introduction' => 'customers#update'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw'

    get 'homes/about' => 'homes#about'

    resources :shipping_addresses, only:  [:index, :create, :edit, :update, :destroy]
    resources :cart_items, only: [:index, :create, :update, :destroy]do
      collection do
        delete "all_destroy"
      end
    end

    get 'items' => 'items#index'
    get 'items/:id' => 'items#show', as: 'item_show'
    get 'search' => 'searches#search'
    resources :genre_searches, only: [:show]

    get 'orders' => 'orders#index'
    get 'orders/new' => 'orders#new'
    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only:  [:create, :show]
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :genre_searches, only: [:show]
    resources :order_searches, only: [:show]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  has_many :shipping_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  has_many :cart_items, dependent: :destroy

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id), notice: "変更を保存しました"
    else
      render :edit
    end

  end

  private

  def customer_params
    params.require(:customer).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:post_code,:address,:phone_number,:email,:is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">

    <h4 class="margin-y"><%= (@customer.last_name + @customer.first_name) %>さんの会員編集画面</h4>
    <%= form_with model: @customer, url: admin_customer_path do |f| %>
    <%= render "layouts/form_errors", model: @customer %>

    <div class="field margin-y">

      <div class="d-flex padding-sm-y">
        <p class="label-width label-name">会員ID</p>
        <p><%= @customer.id %></p>

      </div>

      <div class="d-flex padding-sm-y">
        <p class="label-width label-name">名前</p>
          <%= f.label :last_name, "（姓）", class: "label-position", style: "margin-left: -48px" %>
          <%= f.text_field :last_name, placeholder: "令和", class: "field-width" %>

          <%= f.label :first_name, "（名）", class: "label-position", style: "margin-left: 16px" %>
          <%= f.text_field :first_name, placeholder: "道子", class: "field-width"%>
      </div>

      <div class="d-flex padding-sm-y">
        <p class="label-width label-name">フリガナ</p>
          <%= f.label :last_name_kana, "（セイ）", class: "label-position", style: "margin-left: -64px" %>
          <%= f.text_field :last_name_kana, placeholder: "令和", class: "field-width" %>

          <%= f.label :first_name_kana, "（メイ）", class: "label-position"%>
          <%= f.text_field :first_name_kana, placeholder: "道子", class: "field-width"%>
      </div>

      <div class="d-flex padding-sm-y">
        <%= f.label :post_code, "郵便番号（ハイフンなし）", class: "label-width"  %>
        <%= f.text_field :post_code, placeholder: "0000000", class: "field-width" %>
      </div>

      <div class="d-flex padding-sm-y" style="width: 100%">
        <%= f.label :address, "住所", class: "label-width"  %>
        <%= f.text_field :address, placeholder: "東京都渋谷区代々木神園町0-0", style: "width:472px" %>
      </div>

      <div class="d-flex padding-sm-y">
        <%= f.label :phone_number, "電話番号", class: "label-width"  %>
        <%= f.text_field :phone_number, placeholder: "00000000000", class: "field-width" %>
      </div>

      <div class="d-flex padding-sm-y">
        <%= f.label :email, "メールアドレス", class: "label-width" %>
        <%= f.email_field :email, autocomplete: "email", placeholder: "example@example.com", class: "field-width" %>
      </div>

      <div class="d-flex padding-sm-y">
        <p class="label-width label-name">会員ステータス</p>
        <%= f.radio_button :is_deleted, false %>
      　<%= f.label :is_deleted, "有効", {value: :false, style: "display: inline-block;"} %>
      　<%= f.radio_button :is_deleted, true %>
      　<%= f.label :is_deleted, "退会", {value: :true, style: "display: inline-block;"} %>
      </div>

    </div>
    <div>
      <%= f.submit '変更を保存する' ,class: "btn btn-success" %>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container w-75">
  <div class="margin-y">
    <h4>会員一覧</h4>
    <table class='table table-hover margin-y table-light'>
      <thead>
        <tr>
          <th class="bg-brown">会員ID</th>
          <th class="bg-brown">氏名</th>
          <th class="bg-brown">メールアドレス</th>
          <th class="bg-brown">ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to (customer.last_name + customer.first_name), admin_customer_path(customer.id) %></td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_deleted %>
                <span class="text-muted">退会済み</span>
              <% else %>
                <span class="text-success"><strong>有効</strong></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
  <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
<h4 class="margin-y"><%= (@customer.last_name + @customer.first_name) %>さんの会員詳細</h4>
<div class="row">
  <div class="col">
    <table class="table customer-table table-bordered table-light">
      <tbody>
        <tr>
          <th class="bg-brown">顧客ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th class="bg-brown">氏名</th>
          <td><%= (@customer.last_name + @customer.first_name) %></td>
        </tr>
        <tr>
          <th class="bg-brown">カナ</th>
          <td><%= (@customer.last_name_kana + @customer.first_name_kana) %></td>
        </tr>
        <tr>
          <th class="bg-brown">郵便番号</th>
          <td><%= @customer.post_code.to_s.insert(3, "-") %></td>
        </tr>
        <tr>
          <th class="bg-brown">住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th class="bg-brown">電話番号</th>
          <td><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <th class="bg-brown">メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th class="bg-brown">会員ステータス</th>
          <td>
            <% if @customer.is_deleted %>
              <strong class="text-danger">退会</strong>
            <% else %>
              <strong class="text-success">有効</strong>
            <% end %>
          </td>
        </tr>
      <tbody>
    </table>
    <div class="d-flex justify-content-around">
      <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %>
      <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-primary" %>
    </div>
	</div>
  </div>
</div>
</div>