config/routes.rb
Rails.application.routes.draw do
  root to: 'public/homes#top'

  scope module: :public do
    get 'customers/mypage' => 'customers#show'
    get 'customers/introduction/edit' => 'customers#edit'
    patch 'customers/introduction' => 'customers#update'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw'

    get 'homes/about' => 'homes#about'

    resources :shipping_addresses, only:  [:index, :create, :edit, :update, :destroy]
    resources :cart_items, only: [:index, :create, :update, :destroy]do
      collection do
        delete "all_destroy"
      end
    end

    get 'items' => 'items#index'
    get 'items/:id' => 'items#show', as: 'item_show'
    get 'search' => 'searches#search'
    resources :genre_searches, only: [:show]

    get 'orders' => 'orders#index'
    get 'orders/new' => 'orders#new'
    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only:  [:create, :show]
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :genre_searches, only: [:show]
    resources :order_searches, only: [:show]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :items, through: :order_details
  has_many :order_details, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :post_code, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: {
     wait_payment: 0,
     payment_check: 1,
     producing: 2,
     prepare_shipping: 3,
     shipped: 4
  }, _prefix: true

  def sum_of_price
    item.price_tax * quantity
  end

  def add_tax_price
    (self.price * 1.10).round
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @customer = @order.customer
    @customer_name = @customer.last_name + @customer.first_name
    @order_address = "〒#{@order.post_code.to_s.insert(3, "-")} #{@order.address} #{@customer_name}"
    @order_details = @order.order_details

    @subtotal = 0
    @order_details.each do |order_detail|
      @subtotal += order_detail.item.price * order_detail.quantity
    end
    @postage = 800
    @total = @subtotal + @postage
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    @order.update(order_params)
    if @order.status == "payment_check"
      @order_details.each do |order_detail|
        order_detail.update(production_status: 1)
      end
    end
    redirect_back(fallback_location: root_path)
  end

private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <h4 class="margin-y">注文履歴詳細</h4>

  <table>
    <tbody>
      <tr>
        <th class="field-width">購入者</th>
        <td>
          <%= link_to admin_customer_path(@customer.id) do %>
            <%= @customer_name %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th class="padding-sm-y">注文日</th>
        <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
        <th class="padding-sm-y">配送先</th>
        <td><%= @order_address %></td>
      </tr>
      <tr>
        <th class="padding-sm-y">支払方法</th>
        <td><%= @order.payment_method_i18n %></td>
      </tr>
      <tr>
        <th class="padding-sm-y">注文ステータス</th>
          <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
          <td>
            <div class="d-flex">
              <!--Orderモデルにあるenumハッシュを入手し、keyのみ取ってくる-->
              <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]}, :selected => @order.status, class: "form-control w-50" %>
              <%= f.submit "更新", class: "btn btn-success margin-x" %>
            </div>
          </td>
          <% end %>
      </tr>
    </tbody>
  </table>

  <div class="container">
    <div class="row margin-y">
      <div class="col-md-8">
      <table class="table table-bordered table-light">
        <thead>
          <tr>
            <td class="bg-brown">商品名</td>
            <td class="bg-brown">単価（税込）</td>
            <td class="bg-brown">数量</td>
            <td class="bg-brown">小計</td>
            <td class="bg-brown">製作ステータス</td>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.item.price %></td>
            <td class="text-center"><%= order_detail.quantity %></td>
            <td><%= order_detail.item.price * order_detail.quantity %></td>
            <%= form_with model: @order, url: admin_order_detail_path(order_detail.id), method: :patch do |f| %>
            <td>
              <div class="d-flex justify-content-center">
                <%= f.select :production_status, OrderDetail.production_statuses.keys.map {|k| [I18n.t("enums.order_detail.production_status.#{k}"), k]}, :selected => order_detail.production_status, class: "form-control w-50" %>
                <%= f.submit "更新", class: "btn btn-success margin-x" %>
              </div>
            </td>
              <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      </div>
      <div class="col-md-3 offset-md-1 d-flex align-items-end">
        <table class="table table-bordered table-light">
          <tbody>
            <tr>
              <th class="bg-brown">商品合計</th>
              <td class="text-right"><%= @subtotal.to_s(:delimited) %>円</td>
            </tr>
            <tr>
              <th class="bg-brown">送料</th>
              <td class="text-right"><%= @postage.to_s(:delimited) %>円</td>
            </tr>
            <tr>
              <th class="bg-brown">請求金額合計</th>
              <th class="text-right"><%= @total.to_s(:delimited) %>円</th>
            </tr>
          </tbody>
        </table>
      </div>


    </div>
  </div>
</div>