config/routes.rb
Rails.application.routes.draw do
  root to: 'public/homes#top'

  scope module: :public do
    get 'customers/mypage' => 'customers#show'
    get 'customers/introduction/edit' => 'customers#edit'
    patch 'customers/introduction' => 'customers#update'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw'

    get 'homes/about' => 'homes#about'

    resources :shipping_addresses, only:  [:index, :create, :edit, :update, :destroy]
    resources :cart_items, only: [:index, :create, :update, :destroy]do
      collection do
        delete "all_destroy"
      end
    end

    get 'items' => 'items#index'
    get 'items/:id' => 'items#show', as: 'item_show'
    get 'search' => 'searches#search'
    resources :genre_searches, only: [:show]

    get 'orders' => 'orders#index'
    get 'orders/new' => 'orders#new'
    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only:  [:create, :show]
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :genre_searches, only: [:show]
    resources :order_searches, only: [:show]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item


  def sum_tax_price
    (self.price * 1.10).round * quantity
  end

  validates :quantity, presence:true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  has_many :shipping_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  has_many :cart_items, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

  validates :name, presence:true, uniqueness: true

end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre


  validates :name, presence:true
  validates :price, presence:true, numericality: {only_integer: true, greater_than_or_equal_to: 0}



  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def add_tax_price
    (self.price * 1.10).round
  end


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :items, through: :order_details
  has_many :order_details, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :post_code, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: {
     wait_payment: 0,
     payment_check: 1,
     producing: 2,
     prepare_shipping: 3,
     shipped: 4
  }, _prefix: true

  def sum_of_price
    item.price_tax * quantity
  end

  def add_tax_price
    (self.price * 1.10).round
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum production_status: {
     cannot_start: 0,
     wait_product: 1,
     producing: 2,
     finish_producing: 3
  }, _prefix: true

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  validates :name, presence: true
  validates :address, presence: true
  validates :post_code, presence: true

  belongs_to :customer

  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page])
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
    if @item.update(item_params)
    redirect_to admin_item_path(@item.id)
    else
    render "edit"
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_premitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  def configure_premitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :first_name,
      :first_name_kana,
      :last_name,
      :last_name_kana,
      :post_code,
      :address,
      :phone_number
    ])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer id=”foter”>
  <div class="outer">
    <div class="col-4 mx-auto">
      <div class="inner d-flex justify-content-between align-items-center" style="height: 60px">
    	<span><i class="fa-sharp fa-regular fa-copyright"></i>CopyRight Infratop.inc</span>
      <div>
        <i class="fa-brands fa-facebook" style="margin: 10px"></i>
    		<i class="fa-brands fa-instagram" style="margin: 10px"></i>
    		<i class="fa-brands fa-twitter" style="margin: 10px"></i>
      </div>

    </div>
    </div>

  </div>
</footer>

app/views/layouts/_form_errors.html.erb
<% if model.errors.any? %>
<div>

<h3><%= model.errors.count %>
  <% if model.errors.count >= 2 %>
  errors
  <% else %>
  error
  <% end %>
  prohibited this obj from being saved:
</h3>
<ul>
  <% model.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>

</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light nav-style" style="background-color: #D9BCA3">
  <div class="windowLayout container-fluid">
    <a class="navbar-brand" style="font-family: Ariel; font-size: 26px" href="/">
      <%= image_tag 'logo.png', style: "width: 90px"%>
    </a>
    <% if customer_signed_in? %>
      <p class="m-0">ようこそ <%= "#{current_customer.last_name} #{current_customer.first_name}" %> さん</p>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div>
        <div class="navbar-nav">
          <% if customer_signed_in? %>
            <li class="nav-item px-3">
              <%= link_to "マイページ", customers_mypage_path, class: 'nav-link'  %>
            </li>
            <li class="nav-item px-3">
              <%= link_to "商品一覧", items_path, class: 'nav-link'  %>
            </li>
            <li class="nav-item px-3">
              <%= link_to "カート", cart_items_path, class: 'nav-link'  %>
            </li>
            <li class="nav-item px-3">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link'  %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item px-3">
              <%= link_to "商品一覧", admin_items_path, class: 'nav-link'  %>
            </li>
            <li class="nav-item px-3">
              <%= link_to "会員一覧", admin_customers_path, class: 'nav-link'  %>
            </li>
            <li class="nav-item px-3">
              <%= link_to "注文履歴一覧", admin_path, class: 'nav-link'  %>
            </li>
            <li class="nav-item px-3">
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link'  %>
            </li>
            <li class="nav-item px-3">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link'  %>
            </li>
          <% else %>
            <li class="nav-item px-3">
              <%= link_to "About", homes_about_path, class: 'nav-link'  %>
            </li>
            <li class="nav-item px-3">
              <%= link_to "商品一覧", items_path, class: 'nav-link'  %>
            </li>
            <li class="nav-item px-3">
              <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link'  %>
            </li>
            <li class="nav-item px-3">
              <%= link_to "ログイン", new_customer_session_path, class: 'nav-link'  %>
            </li>
          <% end %>
        </div>
        <div class="search_form d-flex justify-content-end">
          <%= form_with url:search_path, method: :get do |f| %>
          <%= f.text_field :word, placeholder: "商品名", class: "align-middle" %>
          <%= f.submit "検索", class: "btn btn-sm btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_search_genre.html.erb
<section class="col-md-3" style="margin-bottom: 2rem">
  <div class="card border-dark col rounded-0 px-0">
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><h5 class="text-center">ジャンル検索</h5></li>
      <% genres.each do |genre|%>
          <%= link_to genre_search_path(genre.id), class: "link-style" do %>
            <li class="list-group-item border-0 hover-color"><%= genre.name %></li>
          <% end %>
      <% end %>
    </ul>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/a1dd104b6c.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag  'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if flash[:notice].present? %>
    <div class="text-center margin-y">
      <%= flash[:notice]%>
    </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>